<?php

namespace Container2Oc0wvu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivityControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cdtpVWC.App\Controller\ActivityController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cdtpVWC.App\\Controller\\ActivityController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'activityRepository' => ['privates', 'App\\Repository\\ActivityRepository', 'getActivityRepositoryService', true],
            'normalizer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'activityRepository' => 'App\\Repository\\ActivityRepository',
            'normalizer' => '?',
        ]))->withContext('App\\Controller\\ActivityController::index()', $container);
    }
}
