<?php

namespace ContainerMt4KsbS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UTnLvSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._uTnLvS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._uTnLvS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ActivityController::index' => ['privates', '.service_locator.cdtpVWC.App\\Controller\\ActivityController::index()', 'getActivityControllerindexService', true],
            'App\\Controller\\OutingController::add' => ['privates', '.service_locator.NUqX1xr.App\\Controller\\OutingController::add()', 'getOutingControlleraddService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController::add' => ['privates', '.service_locator.Jx15.6S.App\\Controller\\UserController::add()', 'getUserControlleraddService', true],
            'App\\Controller\\UserController::getToken' => ['privates', '.service_locator.uGGQhq0.App\\Controller\\UserController::getToken()', 'getUserControllergetTokenService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.7n.Gtky.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController::verifApiToken' => ['privates', '.service_locator.RkrfOL7.App\\Controller\\UserController::verifApiToken()', 'getUserControllerverifApiTokenService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Controller\\ActivityController:index' => ['privates', '.service_locator.cdtpVWC.App\\Controller\\ActivityController::index()', 'getActivityControllerindexService', true],
            'App\\Controller\\OutingController:add' => ['privates', '.service_locator.NUqX1xr.App\\Controller\\OutingController::add()', 'getOutingControlleraddService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController:add' => ['privates', '.service_locator.Jx15.6S.App\\Controller\\UserController::add()', 'getUserControlleraddService', true],
            'App\\Controller\\UserController:getToken' => ['privates', '.service_locator.uGGQhq0.App\\Controller\\UserController::getToken()', 'getUserControllergetTokenService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.7n.Gtky.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController:verifApiToken' => ['privates', '.service_locator.RkrfOL7.App\\Controller\\UserController::verifApiToken()', 'getUserControllerverifApiTokenService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
        ], [
            'App\\Controller\\ActivityController::index' => '?',
            'App\\Controller\\OutingController::add' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::add' => '?',
            'App\\Controller\\UserController::getToken' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::verifApiToken' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ActivityController:index' => '?',
            'App\\Controller\\OutingController:add' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:add' => '?',
            'App\\Controller\\UserController:getToken' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:verifApiToken' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
