<?php

namespace ContainerU3RaQox;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControlleraddService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QsxXB_1.App\Controller\UserController::add()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QsxXB_1.App\\Controller\\UserController::add()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'serializerInterface' => ['privates', 'serializer', 'getSerializerService', false],
            'userPasswordHasherInterface' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'entityManagerInterface' => '?',
            'serializerInterface' => '?',
            'userPasswordHasherInterface' => '?',
        ]))->withContext('App\\Controller\\UserController::add()', $container);
    }
}
