<?php

namespace Container0Uwwsk4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiRegisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ApiRegister' shared autowired service.
     *
     * @return \App\Service\ApiRegister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ApiRegister.php';

        return $container->privates['App\\Service\\ApiRegister'] = new \App\Service\ApiRegister();
    }
}
