<?php

namespace Container0Uwwsk4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllertestTokenService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UdT0tAy.App\Controller\UserController::testToken()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UdT0tAy.App\\Controller\\UserController::testToken()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'apiRegister' => ['privates', 'App\\Service\\ApiRegister', 'getApiRegisterService', true],
        ], [
            'apiRegister' => 'App\\Service\\ApiRegister',
        ]))->withContext('App\\Controller\\UserController::testToken()', $container);
    }
}
