<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNrdBc74\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNrdBc74/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNrdBc74.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNrdBc74\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNrdBc74\App_KernelDevDebugContainer([
    'container.build_hash' => 'NrdBc74',
    'container.build_id' => 'ec0c0ad9',
    'container.build_time' => 1718818369,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNrdBc74');
