<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0Uwwsk4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0Uwwsk4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0Uwwsk4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0Uwwsk4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0Uwwsk4\App_KernelDevDebugContainer([
    'container.build_hash' => '0Uwwsk4',
    'container.build_id' => 'e081ee51',
    'container.build_time' => 1718633070,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0Uwwsk4');
