<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_activity' => [[], ['_controller' => 'App\\Controller\\ActivityController::index'], [], [['text', '/activity']], [], [], []],
    'app_breed' => [[], ['_controller' => 'App\\Controller\\BreedController::index'], [], [['text', '/breed']], [], [], []],
    'app_outing' => [[], ['_controller' => 'App\\Controller\\OutingController::index'], [], [['text', '/outing']], [], [], []],
    'app_pet' => [[], ['_controller' => 'App\\Controller\\PetController::index'], [], [['text', '/pet']], [], [], []],
    'app_users' => [[], ['_controller' => 'App\\Controller\\UsersController::index'], [], [['text', '/users']], [], [], []],
    'App\Controller\ActivityController::index' => [[], ['_controller' => 'App\\Controller\\ActivityController::index'], [], [['text', '/activity']], [], [], []],
    'App\Controller\BreedController::index' => [[], ['_controller' => 'App\\Controller\\BreedController::index'], [], [['text', '/breed']], [], [], []],
    'App\Controller\OutingController::index' => [[], ['_controller' => 'App\\Controller\\OutingController::index'], [], [['text', '/outing']], [], [], []],
    'App\Controller\PetController::index' => [[], ['_controller' => 'App\\Controller\\PetController::index'], [], [['text', '/pet']], [], [], []],
    'App\Controller\UsersController::index' => [[], ['_controller' => 'App\\Controller\\UsersController::index'], [], [['text', '/users']], [], [], []],
];
