<?php

namespace ContainerNydZm4t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiRegisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ApiRegister' shared autowired service.
     *
     * @return \App\Service\ApiRegister
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Service\\ApiRegister": argument "$token" of method "__construct()" is type-hinted "string", you should configure its value explicitly.');
    }
}
